# This script directs the Travis CI continuous integration build service for the WorldWindJava SDK.
# For more information see https://docs.travis-ci.com/user/customizing-the-build/
language: java

# sudo required is used to install the jq JSON filter used to parse the GitHub API results
sudo: required

jdk:
- oraclejdk8
#- oraclejdk7
#- openjdk6

before_script: |
  # Prepare the runtime scripting environment

  # Ensure script(s) can be executed (req'd if the scripts were authored in Windows)
  chmod +x ./travis/*.sh

  # Install the jq shell filter so we can extract data from GitHub API JSON results
  # See apt configuration: http://docs.travis-ci.com/user/ci-environment/#apt-configuration
  sudo apt-get install -qq jq
  jq --version

script: |
  # Build the project
  if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
      echo Creating the daily tag
      ./travis/add_daily_tag.sh
  else
      echo Building the SDK with ant
      ant worldwind.bundle
      # TODO: Run unit tests
  fi

after_success: |
  # Update GitHub on "tagged" builds
  if [[ -n $TRAVIS_TAG ]]; then
      echo Updating GitHub Releases
      ./travis/update_release.sh
      echo Updating GitHub Pages
      ./travis/update_javadoc.sh
  fi

